# Generated by Django 5.1 on 2024-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0002_remove_category_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='categorys.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assign_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
